# Generated by Django 5.1 on 2024-08-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="daily_limit_open_pouch",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_limit_share_pouch",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_level",
            field=models.IntegerField(default=1),
        ),
    ]
