# Generated by Django 5.0.8 on 2024-08-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
