# Generated by Django 5.0.8 on 2024-08-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='claim_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
