# Generated by Django 5.1 on 2024-08-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_claim_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
