# Generated by Django 5.1 on 2024-08-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_refcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='refcode',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
