# Generated by Django 5.0.8 on 2024-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="user_wallet_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
