# Generated by Django 5.1 on 2024-08-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="giveawaypouch",
            name="expired_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
