# Generated by Django 5.0.8 on 2024-08-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_user_wallet_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="sniff",
            new_name="sniff_point",
        ),
    ]
