# Generated by Django 5.1 on 2024-08-22 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_giveawaypouch_expired_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="giveawaypouch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="giveaway_pouch",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
