# Generated by Django 5.0.8 on 2024-08-27 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_sniff_wallet_sniff_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_number', models.IntegerField(default=0)),
                ('level_name', models.CharField(max_length=255)),
                ('require_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_level_up', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('boost', models.IntegerField(default=0)),
                ('send_envelope', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
