# Generated by Django 5.0.8 on 2024-08-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_userlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giveawaypouch',
            old_name='sniff_coin',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='sniff_coin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
