# Generated by Django 5.1 on 2024-08-27 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_sniff_coin_giveawaypouch_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveawaypouch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giveawaypouch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
