# Generated by Django 5.1 on 2024-08-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_giveawaypouch_created_at_giveawaypouch_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveawaypouch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
