# Generated by Django 5.1 on 2024-08-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_giveawaypouch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstake',
            old_name='sniff_coin_stake_amount',
            new_name='amount',
        ),
    ]
