# Generated by Django 5.1 on 2024-08-29 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_rename_sniff_coin_stake_amount_userstake_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstake',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
