# Generated by Django 5.1 on 2024-08-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_rename_end_datetime_userstake_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstake',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
