# Generated by Django 5.1 on 2024-08-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_userstake_last_claimed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstake',
            old_name='last_claimed',
            new_name='last_claim',
        ),
    ]
