# Generated by Django 5.1 on 2024-08-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_rename_last_claimed_userstake_last_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstake',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userstake',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=255),
        ),
        migrations.AddField(
            model_name='userstake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
