# Generated by Django 5.1 on 2024-08-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_userstake_start_time_userstake_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstake',
            name='earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
